services:
  httpbin:
    image: mccutchen/go-httpbin
    ports:
      - 8080:8080
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
