[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "harp"
version = "0.3.1"
description = ""
authors = ["Romain Dorgueil <romain@makersquad.fr>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.11"
aiosqlite = "^0.19.0"
anyio = "^4.2.0"
asgiref = "^3.7.2"
asyncpg = "^0.29.0"
http-router = "^4.0.0"
httpx = "^0.26.0"
hypercorn = "^0.15.0"
psycopg2-binary = "^2.9.9"
rich = "^13.7.0"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.23" }
sqlalchemy-utils = "^0.41.1"
structlog = "^23.2.0"
svix-ksuid = "^0.6.2"
dataclasses-json = "^0.6.3"
dataclasses-jsonschema = "^2.16.0"
asgimiddlewarestaticfile = "^0.6.0"
aiohttp = "^3.9.1"
multidict = "^6.0.4"
passlib = "^1.7.4"

[tool.poetry.dependencies.essentials-configuration]
path = "./vendors/config"
extras = ["full"]
develop = true

[tool.poetry.dependencies.rodi]
path = "./vendors/rodi"
develop = true

[tool.poetry.dependencies.whistle]
path = "./vendors/whistle"
develop = true

[tool.poetry.group.dev.dependencies]
asgi-tools = "^0.76.0"
black = "^23.12.0"
furo = "^2023.9.10"
honcho = "^1.1.0"
isort = "^5.13.2"
pre-commit = "^3.6.0"
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1" # 0.23 breaks the test suite (https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.23.0)
respx = "^0.20.2"
sphinx = "^7.2.6"
sphinx-autobuild = "^2021.3.14"
sphinx-design = "^0.5.0"
sphinxcontrib-jquery = "^4.1"
watchfiles = "^0.21.0"
dataclasses-jsonschema = "^2.16.0"
pytest-benchmark = { extras = ["histogram"], version = "^4.0.0" }
pytest-cov = "^4.1.0"
sphinx-copybutton = "^0.5.2"
sphinx-sitemap = "^2.5.1"

[tool.poetry.scripts]
harp = 'harp.cli:entrypoint'

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
py_version = 311
profile = "black"
known_first_party = "harp"
known_third_party = "asgiref,httpx,rich,structlog,sqlalchemy,whistle,config,rodi"

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:Deprecated call to:DeprecationWarning",
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]
