[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "harp"
version = "0.1.0"
description = ""
authors = ["Romain Dorgueil <romain@makersquad.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
anyio = "^3.7.1"
asyncpg = "^0.28.0"
blacksheep = "^1.2.18"
essentials-configuration = { extras = ["full"], version = "^2.0.3" }
httpx = "^0.24.1"
hypercorn = "^0.14.4"
nanoid = "^2.0.0"
psycopg2-binary = "^2.9.7"
python-ulid = "^1.1.0"
rich = "^13.4.2"
rodi = ">=1.1.1,<1.2.0"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.20" }
sqlalchemy-utils = "^0.41.1"
structlog = "^23.1.0"
svix-ksuid = "^0.6.2"
asgiref = "^3.7.2"
asgi-tools = "^0.76.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
honcho = "^1.1.0"
pytest = "^7.4.0"
black = "^23.7.0"
isort = "^5.12.0"
pytest-asyncio = "^0.21.1"

[tool.poetry.group.doc.dependencies]
sphinx = "^7.2.3"
sphinx-design = "^0.5.0"
furo = "^2023.8.19"
sphinx-autobuild = "^2021.3.14"
sphinxcontrib-jquery = "^4.1"

[tool.poetry.scripts]
harp = 'harp.cli:entrypoint'

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
py_version = 311

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Deprecated call to:DeprecationWarning",
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]
