apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "harp-proxy.fullname" . }}'
data:
  harp.yaml: |
    proxy:
      endpoints:
        {{- range .Values.endpoints }}
        - port: "{{ .port }}"
          name: "{{ .name }}"
          {{- if .url }}
          url: "{{ .url }}"
          {{- end }}
          {{- if .remote }}
          remote:
            {{ toYaml .remote | nindent 12 }}
          {{- end }}
        {{- end }}

    {{ toYaml .Values.settings | nindent 4 }}
