apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harp-proxy.fullname" . }}
data:
  harp.yaml:  |
    proxy:
      endpoint:
        {{- range .Values.remotes }}
        "{{ .containerPort }}":
          name: "{{ .name }}"
          target: "{{ .endpoint }}"
        {{- end }}
