http_client:
  timeout: 10.0
  cache:
    disabled: false
    controller:
      allow_stale: true
      allow_heuristics: true
      cacheable_methods: [GET]
      cacheable_status_codes: [200, 301, 308]
